title: /kb/log
email: kburman6@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  All the random and crazy things i can do.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kburman.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: kburman6
github_username:  kburman

# Build settings
markdown: kramdown
theme: minima
permalink: pretty
header_pages:
  - project.md
  - resume.md
  - about.md


paginate: 5

plugins:
  - jekyll-feed
  - jekyll-sitemap

disqus:
  shortname: kblog-github

google_analytics: UA-110991819-1


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
