title: /kb/log
email: kburman6@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  All the random and crazy things i can do.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kburman.dev" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: kburman6
github_username:  kburman

# Build settings
markdown: kramdown
theme: minima
permalink: pretty
header_pages:
  - projects.md
  - resume.md
  - about.md


paginate: 5
show_excerpts: true
excerpt_separator: <!--more-->
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-toc
  - jekyll-seo-tag
  - jekyll-avatar

disqus:
  shortname: kblog-github

google_analytics: UA-110991819-3

timezone: Asia/Kolkata
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
